import { EnumLeague } from "@/types";

// Mapping of teams to their respective leagues
export const TEAM_LEAGUE_MAP: Record<string, EnumLeague> = {
  // Premier League
  "Arsenal_FC": EnumLeague.PREMIER_LEAGUE,
  "Aston_Villa_FC": EnumLeague.PREMIER_LEAGUE,
  "AFC_Bournemouth": EnumLeague.PREMIER_LEAGUE,
  "Brighton_Hove_Albion_FC": EnumLeague.PREMIER_LEAGUE,
  "Chelsea_FC": EnumLeague.PREMIER_LEAGUE,
  "Crystal_Palace_FC": EnumLeague.PREMIER_LEAGUE,
  "Everton_FC": EnumLeague.PREMIER_LEAGUE,
  "Fulham_FC": EnumLeague.PREMIER_LEAGUE,
  "Ipswich_Town_FC": EnumLeague.PREMIER_LEAGUE,
  "Leeds_United_FC": EnumLeague.PREMIER_LEAGUE,
  "Leicester_City_FC": EnumLeague.PREMIER_LEAGUE,
  "Liverpool_FC": EnumLeague.PREMIER_LEAGUE,
  "Manchester_City_FC": EnumLeague.PREMIER_LEAGUE,
  "Manchester_United_FC": EnumLeague.PREMIER_LEAGUE,
  "Newcastle_United_FC": EnumLeague.PREMIER_LEAGUE,
  "Nottingham_Forest_FC": EnumLeague.PREMIER_LEAGUE,
  "Sheffield_United_FC": EnumLeague.PREMIER_LEAGUE,
  "Tottenham_Hotspur_FC": EnumLeague.PREMIER_LEAGUE,
  "West_Ham_United_CFC": EnumLeague.PREMIER_LEAGUE,
  "Wolverhampton_Wanderers_FC": EnumLeague.PREMIER_LEAGUE,
  "Blackburn_Rovers_FC": EnumLeague.PREMIER_LEAGUE,
  "Sunderland_AFC": EnumLeague.PREMIER_LEAGUE,
  "Watford_CF": EnumLeague.PREMIER_LEAGUE,

  // La Liga
  "Athletic_Club": EnumLeague.LA_LIGA,
  "Atletico_de_Madrid": EnumLeague.LA_LIGA,
  "CA_Osasuna": EnumLeague.LA_LIGA,
  "Cadiz_CF": EnumLeague.LA_LIGA,
  "FC_Barcelona": EnumLeague.LA_LIGA,
  "Girona_FC": EnumLeague.LA_LIGA,
  "Granada_CF": EnumLeague.LA_LIGA,
  "Malaga_CF": EnumLeague.LA_LIGA,
  "Rayo_Vallecano": EnumLeague.LA_LIGA,
  "RC_Celta_de_Vigo": EnumLeague.LA_LIGA,
  "RC_Deportivo_de_La_Coruna": EnumLeague.LA_LIGA,
  "RCD_Espanyol": EnumLeague.LA_LIGA,
  "RCD_Mallorca": EnumLeague.LA_LIGA,
  "Real_Betis_Balompie": EnumLeague.LA_LIGA,
  "Real_Madrid_CF": EnumLeague.LA_LIGA,
  "Real_Sociedad_de_Footbol": EnumLeague.LA_LIGA,
  "Real_Valladolid_CF": EnumLeague.LA_LIGA,
  "Real_Zaragoza": EnumLeague.LA_LIGA,
  "Sevilla_FC": EnumLeague.LA_LIGA,
  "UD_Almeria": EnumLeague.LA_LIGA,
  "UD_Las_Palmas": EnumLeague.LA_LIGA,
  "Valencia_CF": EnumLeague.LA_LIGA,
  "Villarreal_CF": EnumLeague.LA_LIGA,

  // Serie A
  "AC_Milan": EnumLeague.SERIE_A,
  "ACF_Fiorentina": EnumLeague.SERIE_A,
  "AS_Roma": EnumLeague.SERIE_A,
  "Atalanta_BC": EnumLeague.SERIE_A,
  "Como_1907": EnumLeague.SERIE_A,
  "FC_Internazionale_Milano": EnumLeague.SERIE_A,
  "Juventus_FC": EnumLeague.SERIE_A,
  "Parma_Calcio_1913": EnumLeague.SERIE_A,
  "SS_Lazio": EnumLeague.SERIE_A,
  "SSC_Napoli": EnumLeague.SERIE_A,
  "Torino_FC": EnumLeague.SERIE_A,
  "UC_Sampdoria": EnumLeague.SERIE_A,
  "Venezia_CF": EnumLeague.SERIE_A,

  // Bundesliga
  "Bayer_04_Leverkusen": EnumLeague.BUNDESLIGA,
  "Borussia_Dortmund": EnumLeague.BUNDESLIGA,
  "Borussia_Monchengladbach": EnumLeague.BUNDESLIGA,
  "Eintracht_Frankfurt": EnumLeague.BUNDESLIGA,
  "FC_Augsburg": EnumLeague.BUNDESLIGA,
  "FC_Bayern_Munchen": EnumLeague.BUNDESLIGA,
  "FC_Schalke_04": EnumLeague.BUNDESLIGA,
  "FC_St_Pauli": EnumLeague.BUNDESLIGA,
  "Hamburger_SV": EnumLeague.BUNDESLIGA,
  "RB_Leipzig": EnumLeague.BUNDESLIGA,
  "SV_Werder_Bremen": EnumLeague.BUNDESLIGA,
  "VfL_Wolfsburg": EnumLeague.BUNDESLIGA,
  "ONE_FC_Union_Berlin": EnumLeague.BUNDESLIGA,

  // Ligue 1
  "AS_Monaco": EnumLeague.LIGUE_1,
  "Lille_OSC": EnumLeague.LIGUE_1,
  "Olympique_de_Marseille": EnumLeague.LIGUE_1,
  "Olympique_Lyonnais": EnumLeague.LIGUE_1,
  "Paris_SaintGermain_FC": EnumLeague.LIGUE_1,
  "RC_Lens": EnumLeague.LIGUE_1,
  "RC_Strasbourg_Alsace": EnumLeague.LIGUE_1,
  "Stade_Rennais_FC": EnumLeague.LIGUE_1,

  // National Teams
  "Argentina": EnumLeague.NATIONAL_TEAMS,
  "Belgium": EnumLeague.NATIONAL_TEAMS,
  "Brazil": EnumLeague.NATIONAL_TEAMS,
  "Chile": EnumLeague.NATIONAL_TEAMS,
  "China": EnumLeague.NATIONAL_TEAMS,
  "Colombia": EnumLeague.NATIONAL_TEAMS,
  "Croatia": EnumLeague.NATIONAL_TEAMS,
  "Denmark": EnumLeague.NATIONAL_TEAMS,
  "Ecuador": EnumLeague.NATIONAL_TEAMS,
  "Egypt": EnumLeague.NATIONAL_TEAMS,
  "England": EnumLeague.NATIONAL_TEAMS,
  "France": EnumLeague.NATIONAL_TEAMS,
  "Georgia": EnumLeague.NATIONAL_TEAMS,
  "Germany": EnumLeague.NATIONAL_TEAMS,
  "Greece": EnumLeague.NATIONAL_TEAMS,
  "Guatemala": EnumLeague.NATIONAL_TEAMS,
  "Iceland": EnumLeague.NATIONAL_TEAMS,
  "Ireland": EnumLeague.NATIONAL_TEAMS,
  "Italy": EnumLeague.NATIONAL_TEAMS,
  "Ivory_Coast": EnumLeague.NATIONAL_TEAMS,
  "Jamaica": EnumLeague.NATIONAL_TEAMS,
  "Japan": EnumLeague.NATIONAL_TEAMS,
  "Malta": EnumLeague.NATIONAL_TEAMS,
  "Mexico": EnumLeague.NATIONAL_TEAMS,
  "Morocco": EnumLeague.NATIONAL_TEAMS,
  "Netherlands": EnumLeague.NATIONAL_TEAMS,
  "Nigeria": EnumLeague.NATIONAL_TEAMS,
  "Norway": EnumLeague.NATIONAL_TEAMS,
  "Panama": EnumLeague.NATIONAL_TEAMS,
  "Peru": EnumLeague.NATIONAL_TEAMS,
  "Poland": EnumLeague.NATIONAL_TEAMS,
  "Portugal": EnumLeague.NATIONAL_TEAMS,
  "Romania": EnumLeague.NATIONAL_TEAMS,
  "Scotland": EnumLeague.NATIONAL_TEAMS,
  "Senegal": EnumLeague.NATIONAL_TEAMS,
  "Serbia": EnumLeague.NATIONAL_TEAMS,
  "South_Korea": EnumLeague.NATIONAL_TEAMS,
  "Spain": EnumLeague.NATIONAL_TEAMS,
  "Sweden": EnumLeague.NATIONAL_TEAMS,
  "Switzerland": EnumLeague.NATIONAL_TEAMS,
  "Turkey": EnumLeague.NATIONAL_TEAMS,
  "United_States": EnumLeague.NATIONAL_TEAMS,
  "Uruguay": EnumLeague.NATIONAL_TEAMS,
  "USSR": EnumLeague.NATIONAL_TEAMS,
  "Yugoslavia": EnumLeague.NATIONAL_TEAMS,

  // Rest of the World
  "AFC_Ajax": EnumLeague.REST_OF_THE_WORLD,
  "Al_Hilal_SFC": EnumLeague.REST_OF_THE_WORLD,
  "Al_Nassr_FC": EnumLeague.REST_OF_THE_WORLD,
  "Atlanta_United_FC": EnumLeague.REST_OF_THE_WORLD,
  "Austin_FC": EnumLeague.REST_OF_THE_WORLD,
  "Besiktas_JK": EnumLeague.REST_OF_THE_WORLD,
  "CA_Boca_Juniors": EnumLeague.REST_OF_THE_WORLD,
  "CA_River_Plate": EnumLeague.REST_OF_THE_WORLD,
  "CD_Guadalajara": EnumLeague.REST_OF_THE_WORLD,
  "CD_Palestino": EnumLeague.REST_OF_THE_WORLD,
  "CD_Tenerife": EnumLeague.REST_OF_THE_WORLD,
  "Celtic_FC": EnumLeague.REST_OF_THE_WORLD,
  "CF_Monterrey": EnumLeague.REST_OF_THE_WORLD,
  "Club_America": EnumLeague.REST_OF_THE_WORLD,
  "Club_Brugge_KV": EnumLeague.REST_OF_THE_WORLD,
  "Club_Deportivo_Universidad_Catolica": EnumLeague.REST_OF_THE_WORLD,
  "Club_Olimpia": EnumLeague.REST_OF_THE_WORLD,
  "Clube_Atletico_Mineiro": EnumLeague.REST_OF_THE_WORLD,
  "Corinthians_SC": EnumLeague.REST_OF_THE_WORLD,
  "CR_Flamengo": EnumLeague.REST_OF_THE_WORLD,
  "CR_Vasco_da_Gama": EnumLeague.REST_OF_THE_WORLD,
  "Cruzeiro_EC": EnumLeague.REST_OF_THE_WORLD,
  "CSD_Colo_Colo": EnumLeague.REST_OF_THE_WORLD,
  "FC_Porto": EnumLeague.REST_OF_THE_WORLD,
  "FC_Twente": EnumLeague.REST_OF_THE_WORLD,
  "Fenerbahce_SK": EnumLeague.REST_OF_THE_WORLD,
  "Feyenoord": EnumLeague.REST_OF_THE_WORLD,
  "FK_Crvena_Zvezda": EnumLeague.REST_OF_THE_WORLD,
  "Fluminense_FC": EnumLeague.REST_OF_THE_WORLD,
  "Galatasaray_SK": EnumLeague.REST_OF_THE_WORLD,
  "Gremio_FBPA": EnumLeague.REST_OF_THE_WORLD,
  "Inter_Miami_CF": EnumLeague.REST_OF_THE_WORLD,
  "Kaizer_Chiefs_FC": EnumLeague.REST_OF_THE_WORLD,
  "LA_Galaxy": EnumLeague.REST_OF_THE_WORLD,
  "Lincoln_City_FC": EnumLeague.REST_OF_THE_WORLD,
  "Los_Angeles_FC": EnumLeague.REST_OF_THE_WORLD,
  "New_York_Red_Bulls": EnumLeague.REST_OF_THE_WORLD,
  "Newells_Old_Boys": EnumLeague.REST_OF_THE_WORLD,
  "PSV_Eindhoven": EnumLeague.REST_OF_THE_WORLD,
  "Pumas_UNAM": EnumLeague.REST_OF_THE_WORLD,
  "Rangers_FC": EnumLeague.REST_OF_THE_WORLD,
  "Sanfrecce_Hiroshima": EnumLeague.REST_OF_THE_WORLD,
  "Santos_FC": EnumLeague.REST_OF_THE_WORLD,
  "Sao_Paulo_FC": EnumLeague.REST_OF_THE_WORLD,
  "SE_Palmeiras": EnumLeague.REST_OF_THE_WORLD,
  "SL_Benfica": EnumLeague.REST_OF_THE_WORLD,
  "Sporting_CP": EnumLeague.REST_OF_THE_WORLD,
  "Tigres_UANL": EnumLeague.REST_OF_THE_WORLD,
  "Ulsan_HD_FC": EnumLeague.REST_OF_THE_WORLD,
  "Vissel_Kobe": EnumLeague.REST_OF_THE_WORLD,

  // Mystery
  "Mystery": EnumLeague.MYSTERY,
};

export function getLeagueForTeam(team: string): EnumLeague | undefined {
  return TEAM_LEAGUE_MAP[team];
}

export function formatTeamName(team: string): string {
  return team.replace(/_/g, " ");
}

// Get all teams for a specific league
export function getTeamsForLeague(league: EnumLeague): string[] {
  return Object.entries(TEAM_LEAGUE_MAP)
    .filter(([_, leagueValue]) => leagueValue === league)
    .map(([team]) => team);
}

// Get all teams as array
export function getAllTeams(): string[] {
  return Object.keys(TEAM_LEAGUE_MAP);
}
